language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

services:
  - mongodb

install:
  - "pip install coverage"
  - "pip install nose"
  - "pip install coveralls"
  - "pip install -e ."

script: "python setup.py nosetests --with-coverage --cover-package=depot --cover-erase"

after_success:
  coveralls
